# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tvgl_Cpp <- function(S, n, lambda = 0, beta = 0, penalty_type = "l1", rho = 1, tol = 1e-4, rtol = 1e-4, max_iter = 500L, verbose = 0L) {
    .Call(`_rTVGL_tvgl_Cpp`, S, n, lambda, beta, penalty_type, rho, tol, rtol, max_iter, verbose)
}

